version: "3.8"

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: "Sam16273849"
      POSTGRES_USER: "Sam"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
